version: '3'

services:
    dotnet:
        build: ./dotnet
        image: dotnet-bench
        restart: unless-stopped
        ports:
          - 3000:80
        environment:
          ASPNETCORE_ENVIRONMENT: Production
        mem_limit: 300m
        mem_reservation: 100m
        cpus: 0.5
    dotnet-old:
        build: ./dotnet-old
        image: dotnet-old-bench
        restart: unless-stopped
        ports:
          - 3001:80
        environment:
          ASPNETCORE_ENVIRONMENT: Production
        mem_limit: 300m
        mem_reservation: 100m
        cpus: 0.5
    fastify:
        build: ./fastify
        image: fastify-bench
        restart: unless-stopped
        ports:
          - 3002:3000
        environment:
          NODE_ENV: production
        mem_limit: 300m
        mem_reservation: 100m
        cpus: 0.5
    express:
        build: ./express
        image: express-bench
        restart: unless-stopped
        ports:
          - 3003:3001
        environment:
          NODE_ENV: production
        mem_limit: 300m
        mem_reservation: 100m
        cpus: 0.5
    gin:
        build: ./gin
        image: gin-bench
        restart: unless-stopped
        ports:
          - 3004:8080
        mem_limit: 300m
        mem_reservation: 100m
        cpus: 0.5
    rust-rocket:
        build: ./rust-rocket
        image: rust-rocket-bench
        restart: unless-stopped
        ports:
          - 3005:8000
        environment:
          ROCKET_ADDRESS: 0.0.0.0
          ROCKET_log_level: 'off'
        mem_limit: 300m
        mem_reservation: 100m
        cpus: 0.5

