version: '3'

services:
    dotnet:
        build: ./dotnet
        image: dotnet-bench
        restart: unless-stopped
        ports:
          - 5105:80
        environment:
          ASPNETCORE_ENVIRONMENT: Production
        mem_limit: 300m
        mem_reservation: 100m
        cpus: 2
    dotnet-old:
        build: ./dotnet-old
        image: dotnet-old-bench
        restart: unless-stopped
        ports:
          - 5059:80
        environment:
          ASPNETCORE_ENVIRONMENT: Production
        mem_limit: 300m
        mem_reservation: 100m
        cpus: 2
    fastify:
        build: ./fastify
        image: fastify-bench
        restart: unless-stopped
        ports:
          - 3000:3000
        environment:
          NODE_ENV: production
        mem_limit: 300m
        mem_reservation: 100m
        cpus: 2
    express:
        build: ./express
        image: express-bench
        restart: unless-stopped
        ports:
          - 3001:3001
        environment:
          NODE_ENV: production
        mem_limit: 300m
        mem_reservation: 100m
        cpus: 2
    gin:
        build: ./gin
        image: gin-bench
        restart: unless-stopped
        ports:
          - 3002:8080
        mem_limit: 300m
        mem_reservation: 100m
        cpus: 2
